---
title: "Article 7 : Low level alcohol use during pregnancy can impact child's brain development"
description: 
author:
  - name: Tessa Duhayon
    url: {}
date: 03-14-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
**1. Source of the article with publication date and word count**

Source of the article : https://www.sciencedaily.com/releases/2020/09/200925113422.htm (25/09/20)

Word count : 732

**2. Vocabulary**

/

**3. Analysis table about the study**

| Questions                    | Answers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| ---------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers ?                | University's Matilda Centre for Research in Mental Health and Substance use                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| Published in ? When ?        | in American Journal of Psychiatry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| General topic                | How low alcohol consumption during pregnancy influences child's brain development                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Procedure/What was examined  | -test on 9719 youth (aged 9 to 10 years), -low alcohol = 1-2 drinks per occasion with maximum 6 drinks per week, -low levels of drinking = 1 to 2 drinks per occasion with a maximum of 6 drinks/week                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Conclusions/Discovery        | , -25% of those = exposed to alcohol in-utero, -60% of those = exposed to low alcohol, -40% of those = exposed to heavier levels (three or more per occasion or seven or more drinks per week), -Low levels of alcohol in-utero = + behavioural and psychological problems than unexposed children, -25% increased probability of having an attention deficit hyperactivity disorder diagnosis in children who were exposed to slightly heavier levels of alcohol in the first 6-7 weeks of pregnancy, -a heavier alcohol consumption linked with rule breaking behaviour and agression, with a 30% higher risk of the child being diagnosed with oppositionnal defiant disorder than unexposed children, -brain volume and surface area differed among exposed children which contributed to the psychological and behavioural problems, -the number of drinks consumed during pregnancy ranged from 0-90 with on average 27, -the consumption of alcohol was in majority in the first 6-7 weeks prior to pregnancy knowledge, -the higher levels of alcohol the more severe the outcomes were, -children experienced negative effects even if they were only exposed to low levels of alcohol during very early pregnancy ( around 16 drinks in the first 6-7 weeks) and then the mother stopped drinking      |
| Remaining questions          | /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

