---
title: "Article 4 : Researchers identify molecular connection between meat, dairy diets and cancer risk"
description: 
author:
  - name: Tessa Duhayon
    url:
date: 12-13-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**1. Source of the article with publication date and word count**

Source of the article : https://www.news-medical.net/news/20201022/Researchers-identify-molecular-connection-between-meat-dairy-diets-and-cancer-risk.aspx (13/12/20)

Word count : 537

**2. Vocabulary**

/

**3. Analysis table about the study**

| Questions                    | Answers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| ---------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers ?                | International team of researchers led by Dr. Vered Padler-Karavani of the Department of Cell Research and Immunology at the Schmunis School of Biomedicine and Cancer Research at Tel Aviv University's George S. Wise Faculty of Life Sciences                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| Published in ? When ?        | in BMC Medicine on september 23 2020                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| General topic                | Molecular connection between meat, dairy diets and cancer risk                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Procedure/What was examined  | -Used samples from NutriNet-Santé ( an extensive national nutritional survey conducted in France), -The amount of Neu5Gc sugar in different dairy and meat foods usually found in the french diet was measured by Salam Bashir a PhD student, -The daily Neu5Gc intake of 19.621 grown-ups was calculated based on their food intake that they tracked online over several days, -They took 120 out of 19.621 participants and they checked the levels of the anti-Neu5Gc antibodies in their blood, -With all those informations, they created an index : "Gcemic index" in which different types of food are ranked based on the increase of antibodies they induce (+ can lead possibly to an increase in the risk of cancer) in the body when they are excessively consumed  |
| Conclusions/Discovery        | -They found an interrelationship between high consumption of Neu5Gc and increased development of their antibodies which raises the risk of cancer; so eating a lot of red meat and cheese will develop a great proliferation and a different variety of the antibodies and thus people who eat a lot of meat and cheese may be at higher risk for cancer, especially colorectal cancer.                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Remaining questions          | /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |


Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

