---
title: "Article 2 : Poor nutrition in school years may have created 20 cm height gap across nations"
description: |
  
author:
  - name: Tessa Duhayon
    url:
      https://neurosciencenews.com/soft-drink-teen-aggression-16898/: {}
date: 12-01-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**1. Source of the article with publication date and word count**

Source of the article : https://www.sciencedaily.com/releases/2020/11/201105183840.htm (30/11/20)

Word count : 747

**2. Vocabulary**

/

**3. Analysis table about the study**


| Questions                    | Answers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| ---------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers ?                | Imperial College London, Professor Majid Ezzati = senior author of the study, Dr Andrea Rodriguez Martinez = lead author of the study                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Published in ? When ?        | In the journal = Lancet in 2020                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| General topic                | Poor nutrition in school years may have had repercussion on the height of individuals                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Procedure/What was examined  | -Study made from 1985 to 2019 involving 65 million of children which were aged from 5 to 19 years old, -The height, weight and bmi were measured                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Conclusions/Discovery        | -There is a 20 cm gap between the tallest and shortest nations' individuals, -The tallest individuals aged 19 in 2019 were from northwest and central europe : Nederland, Iceland, Denmark, -The shortest individuals aged 19 in 2019 were from south and southeast asia : Latin America, East Africa, Timor-Leste, Papua New Guinea, Guatemala and Bangladesh, -The most major changes in the children' height over the 35 years were observed in emerging economies : China, South Korea and some parts of southeast Asia, -The height of chinese boys aged 19 increased by 8 cm since 1985, -The height especially  in Sub Saharian nations has dropped or reduced overs the 35 years, -The global height ranking for UK has lowered over the years : The boys were in 28th place but fell down to the 39th place, the girls were in 42th place and fell down to the 49th place, -The individuals aged 19 who had the largest BMI were from : Pacific islands, Middle East, USA and New Zealand, -The ones who had the lowest BMI were from : India and Bangladesh, -In many nations = Children aged 5 had an average height and weight at first but passing this age in certain countries we saw a too little increase of the height but an too much inscrease in weight. That resulted to a lowered potential of healthy growth which is caused by poor nutrition and living environment in school years |
| Remaining questions          | /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |


Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

