---
title: "Article 3 : Plant-based diet boosts metabolism"
description: |

author:
  - name: Tessa Duhayon
    url:
date: 12-06-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
**1. Source of the article with publication date and word count**

Source of the article : https://www.news-medical.net/news/20201130/Study-Plant-based-diet-boosts-metabolism.aspx (30/11/20)

Word count : 604

**2. Vocabulary**

/

**3. Analysis table about the study**

| Questions                    | Answers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| ---------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers ?                | Researchers with the Physicians Committee for Responsible Medicine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| Published in ? When ?        | In JAMA Network Open                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| General topic                | A plant-based diet boosts metabolism                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| Procedure/What was examined  | -The participants who were overweight and had no history of diabetes were randomly put in a group either in the control or intervention group, -For 16 weeks the individuals in the intervention group had to follow a plant-based diet and the other had no diet change, -The participants did not change their exercise, medication routines except if their personal doctor requested it, -The reseachers used indirect calorimetry in order to measure the amount of calories burnt by the participants after a standard meal at the beginning and at the end of the study, -Researchers teamed up with Yale University researchers to keep track of intramyocellular lipid and hepatocellular lipid in a part of the participants using magnetic resonance spectroscopy                                                                                                                                                                                                                                                                                                                                                                                                                              |
| Conclusions/Discovery        | -The number of calories burnt after a meal increased by 18.7% for the plant-based group while the control group saw no significant changes (after 16 weeks), -The plant-based group lost on average 6.4kg in 16 weeks while there was an insignificant change for the control group -The plant-based group also lowered significantly their fat mass and visceral fat volume which is life-threatening, -The fat present in the liver and muscle cells was reduced by 34% and 10% respectively in the plant-based group while the others saw no significant result, -They lowered their chances to develop type 2 diabetes, -The plant-based group saw a decrease of their fasting plasma insulin concentration by 21.6 pmol/L, a decrease in their insulin resistance and an increase of their insulin sensitivity, no changes for the other group, -They reduced their Total cholesterol by 19.3 mg/dL and their LDL cholesterol by 15.5 mg/dL (no changes for the other group), - "Not only did the plant-based group lose weight, but they experienced cardiometabolic improvements that will reduce their risk for type 2 diabetes, heart disease, and other health problems" , said Dr. Kahleova    |
| Remaining questions          | /                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

