---
title: "Article 5 : Childhood diet can alter the gut microbiome for life"
description: |
  
author:
  - name: Tessa Duhayon
    url: {}
date: 03-14-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**1. Source of the article with publication date and word count**

Source of the article : https://www.news-medical.net/news/20210203/Childhood-diet-can-alter-the-gut-microbiome-for-life.aspx (03/02/21)

Word count : 556

**2. Vocabulary**

/

**3. Analysis table about the study**

| Questions                    | Answers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| ---------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Researchers ?                | IUCR researchers (University of California-Riverside)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Published in ? When ?        | in the journal of experimental biology, 2021                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| General topic                | The impact of childhood diet on the microbiome                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Procedure/What was examined  | -They studied mice, they divided them into four groups : 1 = healthy, 2 = "western diet", 3 = exercise, 4 = without exercise, - After 3 weeks they returned to their normal diet and stopped exercising, - week 14 = examination of the diversity and abundance of bacteria in mice                                                                                                                                                                                                                                                                           |
| Conclusions/Discovery        | -Muribaculum intestinale = significant drop in western group, -Microbiome sensitive to the amount of exercise, -Muribaculum bacteria = increased in standard diet group with exercise, -Muribaculum bacteria = reduced in high fat diet group whether they had exercise or not, -Increase in similar bacteria species (after five weeks of treadmeal training = discovery found by other researchers) = exercise may increase its presence, -globally = early-life western diet had more long-lasting effects on the microbiome than did early-life exercise  |
| Remaining questions          | -MI and other bacteria that belongs to the MI family = might influence the amount of energy available to its host + other functions of this type, - when do the first changes happen in the mouse microbiome and if they extend into even later phases of life                                                                                                                                                                                                                                                                                                |

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

